service: serverless-dynamodb-cri-app

custom:
  serviceId: 
  region:
  lastestStreamARN: 

provider:
  name: aws
  runtime: nodejs8.10
  stage: dev
  region: us-east-1
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:DescribeStream
        - dynamodb:GetRecords
        - dynamodb:GetShardIterator
        - dynamodb:ListStreams
        - dynamodb:GetItem 
        - dynamodb:PutItem 
      Resource: arn:aws:dynamodb:${self:custom.region}:${self:custom.serviceId}:table/dynamodb-cri

functions:
  api:
    handler: index.handler # reference the file and exported method
    name: api-${self:provider.stage}
    description: The lambda function containing the API
    events: # events trigger lambda functions
      - http: # this is an API Gateway HTTP event trigger
          path: /
          method: ANY
          cors: true
      - http: # all routes get proxied to the Express router
          path: /{proxy+}
          method: ANY
          cors: true
    package:
      include:
        - src/**
        - node_modules/**
  hookstreams:
    handler: lambdaFunction/mantainIndexes.handler
    name: mantain-${self:provider.stage}
    description: Function to keep updated the indexes
    memorySize: 512
    timeout: 30
    events:
      - stream: ${self:custom.lastestStreamARN}
    package:
      include:
        - dist/**
        - node_modules/**
resources:
  Resources:
    dynamodbcriTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: dynamodb-cri
        AttributeDefinitions:
          - AttributeName: pk
            AttributeType: S
          - AttributeName: sk
            AttributeType: S
          - AttributeName: gk
            AttributeType: S  
        KeySchema:
          - AttributeName: pk
            KeyType: HASH
          - AttributeName: sk
            KeyType: RANGE
        ProvisionedThroughput:
          ReadCapacityUnits: '1'
          WriteCapacityUnits: '1'
        GlobalSecondaryIndexes:
          - IndexName: gsik
            KeySchema:
              - AttributeName: sk
                KeyType: HASH
              - AttributeName: gk
                KeyType: RANGE
            Projection:
              ProjectionType: ALL
            ProvisionedThroughput:
              ReadCapacityUnits: '1'
              WriteCapacityUnits: '1'
        StreamSpecification:
          StreamViewType: NEW_AND_OLD_IMAGES