service: serverless-dynamodb-cri-app

provider:
  name: aws
  runtime: nodejs8.10
  stage: dev
  region: us-east-1

functions:
  app:
    handler: index.handler # reference the file and exported method
    events: # events trigger lambda functions
      - http: # this is an API Gateway HTTP event trigger
          path: /
          method: ANY
          cors: true
      - http: # all routes get proxied to the Express router
          path: /{proxy+}
          method: ANY
          cors: true
    package:
      include:
        - src/**
        - node_modules/**
resources:
  Resources:
    dynamodbcriTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: dynamodb-cri
        AttributeDefinitions:
          - AttributeName: pk
            AttributeType: S
          - AttributeName: sk
            AttributeType: S
          - AttributeName: gk
            AttributeType: S  
        KeySchema:
          - AttributeName: pk
            KeyType: HASH
          - AttributeName: sk
            KeyType: RANGE
        ProvisionedThroughput:
          ReadCapacityUnits: '1'
          WriteCapacityUnits: '1'
        GlobalSecondaryIndexes:
          - IndexName: gsik
            KeySchema:
              - AttributeName: sk
                KeyType: HASH
              - AttributeName: gk
                KeyType: RANGE
            Projection:
              ProjectionType: ALL
            ProvisionedThroughput:
              ReadCapacityUnits: '1'
              WriteCapacityUnits: '1'